name: Windows binaries

on:
  workflow_dispatch:
    inputs:
      tdlib_git_ref:
        description: 'TdLib tag/commit'
        required: true
        default: 'v1.8.0'

jobs:
  build-windows-java:
    runs-on: windows-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Checkout TdLib
        uses: actions/checkout@v2
        with:
          repository: tdlib/td
          ref: ${{ github.event.inputs.tdlib_git_ref }}
          path: tdrepo

      - name: Run build script
        run: ${{ github.workspace }}/.github/scripts/windows/td-build.ps1
        shell: pwsh
        working-directory: ${{ github.workspace }}/tdrepo
        
      - name: Archive binary libs
        uses: actions/upload-artifact@v3
        with:
          name: windows-bin
          path: ${{ github.workspace }}/tdrepo/tdlib/bin/*.dll
